version: "3"

services:
  php:
    container_name: php
    image: php:8-fpm-alpine
    working_dir: ${APP_DIR:-/app}
    environment:
      RYANAIR_BASE_URI: ${RYANAIR_BASE_URI}
    volumes:
      - .:${APP_DIR:-/app}

  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    restart: always
    environment:
      APP_DIR: ${APP_DIR:-/app}
    volumes:
      - ./.docker/nginx/templates:/etc/nginx/templates
      - .:${APP_DIR:-/app}
    ports:
      - 80:80
    depends_on:
      - php
