name: CI

on: [push]

jobs:
  build-test:
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      
    - name: Install new dependencies
      uses: php-actions/composer@v6

    - name: Run unit tests
      uses: php-actions/composer@v6
      with:
        command: run-script
        args: test